<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_content']['up_postfinanceJumpToComplete']	= array('Weiterleitungsseite nach Bezahlung','Wählen Sie die Seite, auf die der Benutzer nach der Bezahlung weitergeleitet werden soll.');